import type { CartItem } from '../context/CartContext';

export type HomeTabKey = 'home' | 'product' | 'service' | 'blog' | 'profile';

export type RootStackParamList = {
  WelcomeSplash: undefined;
  WelcomeChoice: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  OTPPassword: { email: string } | undefined;
  ResetPassword: undefined;
  Home: { initialTab?: HomeTabKey } | undefined;
  ProductList: undefined;
  ProductDetail: { productSlug: string; product?: any };
  ServiceList: undefined;
  ServiceDetail: { serviceId: string; service?: any };
  BlogList: undefined;
  BlogDetail: { slug: string; blog?: any };
  Cart: undefined;
  Checkout: undefined;
  OrderSuccess: { orderCode: string; phone: string };
  Payment: undefined;
  Booking: { serviceId?: string; service?: any } | undefined;
  MyBookings: undefined;
  BookingDetail: { bookingId: string };
  AddressList: undefined;
  AddressForm: { address?: any };
  OrderList: undefined;
  OrderDetail: { orderId: string };
  PetList: undefined;
  PetForm: { pet?: any };
  PetDetail: { petId: string };
  TransactionHistory: undefined;
  ReviewList: undefined;
  FavoriteList: undefined;
  PersonalInfo: undefined;
  ChangePassword: undefined;
  CouponList: undefined;
  BreedList: undefined;
  BoardingCages: undefined;
  BoardingBookings: undefined;
  BoardingBookingCreate: { cageId: string; checkInDate?: string; checkOutDate?: string };
  BoardingBookingDetail: { bookingId: string };
  BoardingHotel: undefined;
  MyBoardingBookings: undefined;
  Overview: undefined;
  AccountFeature: { title: string; description?: string };
  StaffLogin: undefined;
  StaffHome: undefined;
  StaffTaskList: { date?: string } | undefined;
  StaffCareDetail: { bookingId: string; booking: any };
  StaffCustomerList: undefined;
  StaffCages: undefined;
  StaffChat: undefined;
  StaffProfile: undefined;
  StaffWorkSchedule: undefined;
  StaffScheduleCalendar: undefined;
  StaffShiftList: undefined;
  PetCareTemplate: undefined;
  StaffBoardingBookingList: undefined;
  StaffBoardingBookingCreate: undefined;
  StaffReviewList: undefined;
  DepartmentList: undefined;
};
